### ISSUE TITLE
Error running sentence transformer example

### ISSUE THREAD

**Issue by complexitysoftware** [philschmid/optimum-transformers-optimizations#1]
I have hit the error:
```
RuntimeError: Failed to import optimum.onnxruntime.optimization because of the following error (look up to see its traceback):
cannot import name 'cached_path' from 'transformers.file_utils' (d:\Programs\anaconda3\envs\optimum\lib\site-packages\transformers\file_utils.py)
```
when running the sentence transformer / optimum example from here: https://github.com/philschmid/optimum-transformers-optimizations/blob/master/sentence-transformers.ipynb
I did the following:
- conda create -y -n optimum python=3.9
- conda activate optimum   
- Install ipykernel
- Run sentence-transformers.ipynb from https://github.com/philschmid/optimum-transformers-optimizations/blob/master/sentence-transformers.ipynb

The error occurs in the cell:
```
from optimum.onnxruntime import ORTOptimizer
from optimum.onnxruntime.configuration import OptimizationConfig

# create ORTOptimizer and define optimization configuration
optimizer = ORTOptimizer.from_pretrained(model_id, feature=model.pipeline_task)
optimization_config = OptimizationConfig(optimization_level=99) # enable all optimizations

# apply the optimization configuration to the model
optimizer.export(
    onnx_model_path=onnx_path / "model.onnx",
    onnx_optimized_model_output_path=onnx_path / "model-optimized.onnx",
    optimization_config=optimization_config,
)
```
I tried installing `!pip install "optimum[onnxruntime]==1.4.1" evaluate mkl-include mkl` but got an error with ORTModelForFeatureExtraction
Thanks for your code this looks like the best example of using sentence transformers with ONNX after a lot of looking.

PS I just tried the notebook on Colab and it has the same issue there. This may well be a Transformer issue rather than any issue with the sentence-transformers.ipynb notebook.

**Comment by philschmid** [comment]
Hello @complexitysoftware,

I update all examples today to the newest version. Could you please try to rerun them

**Comment by complexitysoftware** [comment]
Hi @philschmid 

I tested the new version now at the URL https://github.com/philschmid/optimum-transformers-optimizations/blob/master/sentence-transformers.ipynb and it runs very successfully.  Thank you for that and all your efforts.
